name: Deployment pipeline

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install server dependencies
        run: cd server && npm install
      - name: Install client dependencies
        run: cd client && npm install
      - name: check style
        run: cd server && npm run lint
      - name: production build
        run: |
          cd server &&
          touch .env
          echo MONGODB_URI=$MONGODB_URI >> .env
          echo TEST_MONGODB_URI=$TEST_MONGODB_URI >> .env
          echo PORT=$PORT >> .env
          echo SECRET=$SECRET >> .env
          npm run build:ui
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: ${{ secrets.PORT }}
      - name: server tests
        run: cd server && npm test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: cd client && npm run test:e2e
          start: cd server && npm run start
          wait-on: http://localhost:3001